#!/bin/bash
#
# 02-setup-cloudflared.sh
# Install and configure Cloudflare Tunnel for Zero Trust remote SSH access
#
# What this does:
#   - Installs cloudflared (Cloudflare's tunnel daemon)
#   - Creates a secure tunnel from your Mac to Cloudflare's edge network
#   - No port forwarding, no public IP, no firewall holes
#   - Enables both Browser SSH and WARP private network access
#
# Prerequisites:
#   - A domain managed by Cloudflare (free plan works)
#   - A Cloudflare Zero Trust account (free for up to 50 users)
#   - SSH enabled on your Mac (run 01-setup-mac-ssh.sh first)
#
# Usage: bash scripts/02-setup-cloudflared.sh
#

set -e

echo "============================================"
echo "  Step 2: Cloudflare Tunnel Setup"
echo "============================================"
echo ""
echo "  ZERO TRUST PRINCIPLE:"
echo "  Instead of exposing ports to the internet (traditional VPN),"
echo "  Cloudflare Tunnel creates an OUTBOUND-ONLY connection from"
echo "  your Mac to Cloudflare's edge. Nothing is publicly exposed."
echo ""
echo "  Your Mac ---outbound---> Cloudflare Edge <---authenticated--- Your Phone"
echo ""

# -----------------------------------------------
# Step 1: Install cloudflared
# -----------------------------------------------
echo "--- Step 2.1: Install cloudflared ---"
if command -v cloudflared &>/dev/null; then
    echo "[OK] cloudflared is already installed: $(cloudflared --version)"
else
    echo "Installing cloudflared via Homebrew..."
    if ! command -v brew &>/dev/null; then
        echo "[ERROR] Homebrew not found. Install it first: https://brew.sh"
        exit 1
    fi
    brew install cloudflared
    echo "[OK] cloudflared installed: $(cloudflared --version)"
fi
echo ""

# -----------------------------------------------
# Step 2: Authenticate with Cloudflare
# -----------------------------------------------
echo "--- Step 2.2: Authenticate with Cloudflare ---"
if [[ -f "$HOME/.cloudflared/cert.pem" ]]; then
    echo "[OK] Already authenticated (cert.pem found)."
else
    echo "This will open your browser to log in to Cloudflare."
    echo "Select the domain you want to use for SSH access."
    echo ""
    read -p "Press Enter to open the browser for authentication..."
    cloudflared login
    echo "[OK] Authentication complete."
fi
echo ""

# -----------------------------------------------
# Step 3: Create a tunnel
# -----------------------------------------------
echo "--- Step 2.3: Create a Tunnel ---"
echo ""
read -p "Enter a name for your tunnel (e.g., mac-remote): " TUNNEL_NAME
TUNNEL_NAME=${TUNNEL_NAME:-mac-remote}

# Check if tunnel already exists
if cloudflared tunnel list | grep -q "$TUNNEL_NAME"; then
    echo "[OK] Tunnel '$TUNNEL_NAME' already exists."
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
else
    echo "Creating tunnel '$TUNNEL_NAME'..."
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo "[OK] Tunnel created with ID: $TUNNEL_ID"
fi
echo ""

# -----------------------------------------------
# Step 4: Configure the tunnel
# -----------------------------------------------
echo "--- Step 2.4: Configure the Tunnel ---"
echo ""
read -p "Enter your domain (e.g., yourdomain.com): " DOMAIN
DOMAIN=${DOMAIN:-yourdomain.com}

SSH_HOSTNAME="ssh.${DOMAIN}"
USERNAME=$(whoami)
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || echo "192.168.1.x")

CONFIG_FILE="$HOME/.cloudflared/config.yml"

if [[ -f "$CONFIG_FILE" ]]; then
    echo "[WARN] Config file already exists at $CONFIG_FILE"
    read -p "Overwrite? (y/n): " overwrite
    if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
        echo "[SKIP] Keeping existing config."
        echo ""
        cat "$CONFIG_FILE"
        echo ""
    fi
fi

if [[ ! -f "$CONFIG_FILE" ]] || [[ "$overwrite" == "y" ]] || [[ "$overwrite" == "Y" ]]; then
    cat > "$CONFIG_FILE" << EOF
# Cloudflare Tunnel Configuration
# Generated by setup script on $(date +%Y-%m-%d)

tunnel: ${TUNNEL_ID}
credentials-file: /Users/${USERNAME}/.cloudflared/${TUNNEL_ID}.json

# Enable WARP routing for private network access (Method 3: WARP + Termius)
# This lets your phone reach your Mac's local IP through the tunnel
warp-routing:
  enabled: true

ingress:
  # Route ${SSH_HOSTNAME} to local SSH server
  - hostname: ${SSH_HOSTNAME}
    service: ssh://localhost:22

  # Catch-all rule (required) - returns 404 for unmatched requests
  - service: http_status:404
EOF
    echo "[OK] Config written to $CONFIG_FILE"
fi
echo ""

# -----------------------------------------------
# Step 5: Add DNS route
# -----------------------------------------------
echo "--- Step 2.5: Add DNS Route ---"
echo "This creates a CNAME record: $SSH_HOSTNAME -> your tunnel"
echo ""
cloudflared tunnel route dns "$TUNNEL_NAME" "$SSH_HOSTNAME" 2>/dev/null || true
echo "[OK] DNS route configured for $SSH_HOSTNAME"
echo ""

# -----------------------------------------------
# Step 6: Add private network route (for WARP)
# -----------------------------------------------
echo "--- Step 2.6: Add Private Network Route (for WARP + Termius) ---"
echo ""
echo "Your Mac's local IP: $LOCAL_IP"
read -p "Use this IP for private network route? (y/n): " use_ip
if [[ "$use_ip" == "y" || "$use_ip" == "Y" ]]; then
    cloudflared tunnel route ip add "${LOCAL_IP}/32" "$TUNNEL_NAME" 2>/dev/null || true
    echo "[OK] Private network route added: ${LOCAL_IP}/32 -> $TUNNEL_NAME"
else
    read -p "Enter your Mac's IP: " CUSTOM_IP
    cloudflared tunnel route ip add "${CUSTOM_IP}/32" "$TUNNEL_NAME" 2>/dev/null || true
    echo "[OK] Private network route added: ${CUSTOM_IP}/32 -> $TUNNEL_NAME"
fi
echo ""

# -----------------------------------------------
# Step 7: Install as system service
# -----------------------------------------------
echo "--- Step 2.7: Install as System Service ---"
echo ""
echo "This ensures the tunnel starts automatically on boot."
echo ""

PLIST_FILE="/Library/LaunchDaemons/com.cloudflare.cloudflared.plist"
CLOUDFLARED_PATH=$(which cloudflared)

if [[ -f "$PLIST_FILE" ]]; then
    echo "[OK] LaunchDaemon already exists."
    read -p "Reinstall? (y/n): " reinstall
fi

if [[ ! -f "$PLIST_FILE" ]] || [[ "$reinstall" == "y" ]]; then
    echo "Creating LaunchDaemon (requires admin password)..."
    sudo tee "$PLIST_FILE" > /dev/null << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.cloudflare.cloudflared</string>
    <key>ProgramArguments</key>
    <array>
      <string>${CLOUDFLARED_PATH}</string>
      <string>--config</string>
      <string>/Users/${USERNAME}/.cloudflared/config.yml</string>
      <string>tunnel</string>
      <string>run</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/Library/Logs/com.cloudflare.cloudflared.out.log</string>
    <key>StandardErrorPath</key>
    <string>/Library/Logs/com.cloudflare.cloudflared.err.log</string>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
  </dict>
</plist>
EOF
    sudo launchctl load "$PLIST_FILE"
    echo "[OK] Service installed and started."
fi
echo ""

# -----------------------------------------------
# Step 8: Verify
# -----------------------------------------------
echo "--- Step 2.8: Verify Tunnel ---"
echo ""
sleep 2
cloudflared tunnel list
echo ""

echo "============================================"
echo "  Cloudflare Tunnel Setup Complete!"
echo "============================================"
echo ""
echo "  Your tunnel: $TUNNEL_NAME ($TUNNEL_ID)"
echo "  SSH hostname: $SSH_HOSTNAME"
echo "  Config file:  $CONFIG_FILE"
echo ""
echo "  NEXT: Configure Cloudflare Zero Trust Dashboard"
echo "  Run: bash scripts/02b-configure-zero-trust.sh"
echo ""
echo "  Or check the README for manual dashboard steps."
echo ""
