#!/bin/bash
#
# 02b-configure-zero-trust.sh
# Interactive guide for configuring Cloudflare Zero Trust Dashboard
#
# These steps must be done in the Cloudflare dashboard (web UI).
# This script walks you through each setting step by step.
#
# Usage: bash scripts/02b-configure-zero-trust.sh
#

echo "============================================"
echo "  Cloudflare Zero Trust Dashboard Setup"
echo "============================================"
echo ""
echo "  Open: https://one.dash.cloudflare.com"
echo ""
echo "  ZERO TRUST MEANS:"
echo "  - Never trust, always verify"
echo "  - Every connection requires authentication"
echo "  - No device is trusted by default, even on your own network"
echo "  - Access is granted per-session, per-resource"
echo ""

# -----------------------------------------------
# Part A: Browser SSH (Method 2)
# -----------------------------------------------
echo "============================================"
echo "  Part A: Browser SSH Setup"
echo "============================================"
echo ""
echo "  This lets you open a terminal in your browser from ANY device."
echo "  No apps needed - just a web browser."
echo ""
read -p "Press Enter to continue..."
echo ""

echo "  STEP A1: Enable One-time PIN authentication"
echo "  -------------------------------------------"
echo "  Go to: Settings > Authentication > Login methods"
echo "  Action: Enable 'One-time PIN'"
echo ""
echo "  WHY: This sends a verification code to your email."
echo "       Only people with access to your email can connect."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "  STEP A2: Create an Access Application"
echo "  --------------------------------------"
echo "  Go to: Access controls > Applications > Add an application"
echo "  Select: 'Self-hosted'"
echo ""
echo "  Configure:"
echo "    Application name:  Mac SSH"
echo "    Session Duration:  1 month (or your preference)"
echo "    Public hostname:"
echo "      Subdomain: ssh"
echo "      Domain:    yourdomain.com"
echo "    Browser rendering: SSH    <-- CRITICAL! Must be 'SSH', not 'Disabled'"
echo ""
echo "  WHY 'SSH' rendering: This tells Cloudflare to render an SSH terminal"
echo "  in the browser. If set to 'Disabled', you'll download a text file instead."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "  STEP A3: Add an Access Policy"
echo "  -----------------------------"
echo "  Policy name:  Allow me"
echo "  Action:       Allow"
echo "  Selector:     Emails"
echo "  Value:        your-email@example.com"
echo ""
echo "  ZERO TRUST: Only the emails you explicitly list can access"
echo "  your Mac. Everyone else is blocked - no exceptions."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "  [OK] Browser SSH is configured!"
echo "  Test it: Open https://ssh.yourdomain.com in any browser"
echo ""

# -----------------------------------------------
# Part B: WARP + Termius (Method 3)
# -----------------------------------------------
echo "============================================"
echo "  Part B: WARP + Termius (Native SSH via Tunnel)"
echo "============================================"
echo ""
echo "  This lets you use Termius (native SSH app) on your phone"
echo "  to connect over cellular/WiFi through Cloudflare's tunnel."
echo ""
read -p "Press Enter to continue..."
echo ""

echo "  STEP B1: Enable Gateway Proxy  *** MOST COMMONLY MISSED STEP ***"
echo "  ----------------------------------------------------------------"
echo "  Go to: Traffic policies > Traffic settings"
echo "  Find: 'Allow Secure Web Gateway to proxy traffic'"
echo "  Action: Turn it ON"
echo "  Enable: TCP, UDP, and ICMP"
echo ""
echo "  WHY: Without this, WARP connects but 'is_gateway' stays false,"
echo "  and private network routing silently fails. This is the #1 issue."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "  STEP B2: Configure Split Tunnels"
echo "  --------------------------------"
echo "  Go to: Team & Resources > Devices > Device profiles > Default"
echo "  Find: Split Tunnels (set to 'Exclude IPs and domains')"
echo "  Action: REMOVE '192.168.0.0/16' from the exclude list"
echo ""
echo "  WHY: By default, WARP bypasses local network IPs. By removing"
echo "  192.168.0.0/16 from the exclude list, you tell WARP to route"
echo "  those IPs through the tunnel, reaching your Mac."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "  STEP B3: Add Gateway Network Policy"
echo "  ------------------------------------"
echo "  Go to: Traffic policies > Firewall policies > Network tab"
echo "  Add a policy:"
echo "    Name:     Allow Mac SSH"
echo "    Selector: Destination IP"
echo "    Operator: in"
echo "    Value:    YOUR_MAC_IP/32  (e.g., 192.168.1.x/32)"
echo "    Action:   Allow"
echo ""
echo "  WHY: This explicitly allows traffic to your Mac's private IP."
echo "  Without it, Gateway may silently drop the connection."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "  STEP B4: Configure Device Enrollment"
echo "  -------------------------------------"
echo "  Go to: Settings > WARP Client > Device enrollment permissions"
echo "  Add a rule:"
echo "    Selector:       Emails"
echo "    Value:          your-email@example.com"
echo "    Authentication: One-time PIN"
echo ""
echo "  WHY: This controls which devices can join your Zero Trust network."
echo "  Only your email can enroll a device."
echo ""
read -p "Done? Press Enter to continue..."
echo ""

echo "============================================"
echo "  Part C: iPhone Setup for WARP"
echo "============================================"
echo ""
echo "  1. Install '1.1.1.1: Faster Internet' from the App Store"
echo "  2. Open the app > Settings > Account"
echo "  3. Tap 'Login to Cloudflare Zero Trust'"
echo "  4. Enter your Zero Trust organization name"
echo "  5. Install the VPN profile when prompted"
echo "  6. IMPORTANT: Enter Zero Trust mode FIRST, then connect WARP"
echo "  7. Verify WARP shows as connected"
echo ""
echo "  Then in Termius:"
echo "  - Host: your Mac's local IP (e.g., 192.168.1.x)"
echo "  - Port: 22"
echo "  - Username: your Mac username"
echo "  - Password: your Mac login password"
echo ""

echo "============================================"
echo "  Zero Trust Dashboard Setup Complete!"
echo "============================================"
echo ""
echo "  Run the verification script to test everything:"
echo "  bash scripts/04-verify-connection.sh"
echo ""
