#!/bin/bash
#
# 06-setup-ssh-config.sh
# Set up SSH config with ProxyJump for multi-hop access
#
# What this does:
#   - Creates or updates ~/.ssh/config with jump host entries
#   - Configures ProxyJump for machines reachable only via LAN
#   - Adds keepalive settings to prevent dropped connections
#   - Sets up Bonjour/.local hostname resolution
#
# Usage: bash scripts/06-setup-ssh-config.sh
#

set -e

echo "============================================"
echo "  Step 6: SSH Config & ProxyJump Setup"
echo "============================================"
echo ""
echo "  ProxyJump lets you reach machines through a jump host"
echo "  with a single command. No manual two-step SSH needed."
echo ""
echo "  Example: ssh mac-mini"
echo "  Behind the scenes: you → mac-studio → mac-mini"
echo ""

SSH_DIR="$HOME/.ssh"
SSH_CONFIG="$SSH_DIR/config"

# -----------------------------------------------
# Step 1: Ensure .ssh directory exists
# -----------------------------------------------
echo "--- Step 6.1: Check SSH directory ---"
echo ""

if [[ ! -d "$SSH_DIR" ]]; then
    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"
    echo "[OK] Created $SSH_DIR"
else
    echo "[OK] $SSH_DIR exists"
fi
echo ""

# -----------------------------------------------
# Step 2: Gather information
# -----------------------------------------------
echo "--- Step 6.2: Configure your hosts ---"
echo ""

# Jump host (reachable via Tailscale)
echo "=== Jump Host (the machine with Tailscale) ==="
echo ""
read -p "Jump host SSH alias (e.g., mac-studio): " JUMP_ALIAS
read -p "Jump host hostname or Tailscale name (e.g., mac-studio): " JUMP_HOSTNAME
read -p "Jump host username: " JUMP_USER

echo ""

# Target host (reachable only via LAN)
echo "=== Target Host (reachable via jump host) ==="
echo ""
read -p "Target host SSH alias (e.g., mac-mini): " TARGET_ALIAS
read -p "Target .local hostname (e.g., mac-mini.local): " TARGET_HOSTNAME
read -p "Target username: " TARGET_USER
read -p "Target IP address (backup, optional): " TARGET_IP

echo ""

# -----------------------------------------------
# Step 3: Generate SSH config
# -----------------------------------------------
echo "--- Step 6.3: Generate SSH config ---"
echo ""

CONFIG_BLOCK="
# === Remote Access Configuration ===
# Generated by cloudflare-remote-ssh-guide
# $(date)

# Global settings -- keepalive to prevent disconnections
Host *
    ServerAliveInterval 60
    ServerAliveCountMax 3
    AddKeysToAgent yes

# Jump host -- reachable via Tailscale from anywhere
Host $JUMP_ALIAS
    HostName $JUMP_HOSTNAME
    User $JUMP_USER

# Target -- reachable via jump host (ProxyJump)
Host $TARGET_ALIAS
    HostName $TARGET_HOSTNAME
    User $TARGET_USER
    ProxyJump $JUMP_ALIAS"

# Add IP-based fallback if provided
if [[ -n "$TARGET_IP" ]]; then
    CONFIG_BLOCK="$CONFIG_BLOCK

# Target (IP fallback) -- use if .local hostname fails
Host ${TARGET_ALIAS}-ip
    HostName $TARGET_IP
    User $TARGET_USER
    ProxyJump $JUMP_ALIAS"
fi

CONFIG_BLOCK="$CONFIG_BLOCK
# === End Remote Access Configuration ==="

echo "Generated config:"
echo "---"
echo "$CONFIG_BLOCK"
echo "---"
echo ""

# -----------------------------------------------
# Step 4: Write to SSH config
# -----------------------------------------------
echo "--- Step 6.4: Write SSH config ---"
echo ""

MARKER="# === Remote Access Configuration ==="

if [[ -f "$SSH_CONFIG" ]] && grep -q "$MARKER" "$SSH_CONFIG"; then
    echo "[WARN] Remote access config already exists in $SSH_CONFIG"
    read -p "Replace existing config? (y/n): " replace
    if [[ "$replace" == "y" || "$replace" == "Y" ]]; then
        # Remove existing block
        sed -i '' "/$MARKER/,/# === End Remote Access Configuration ===/d" "$SSH_CONFIG"
        echo "$CONFIG_BLOCK" >> "$SSH_CONFIG"
        echo "[OK] Replaced existing config in $SSH_CONFIG"
    else
        echo "[SKIP] Config not modified."
    fi
else
    if [[ -f "$SSH_CONFIG" ]]; then
        echo "" >> "$SSH_CONFIG"
    fi
    echo "$CONFIG_BLOCK" >> "$SSH_CONFIG"
    chmod 600 "$SSH_CONFIG"
    echo "[OK] Added config to $SSH_CONFIG"
fi
echo ""

# -----------------------------------------------
# Step 5: Test connectivity
# -----------------------------------------------
echo "--- Step 6.5: Test connectivity ---"
echo ""

echo "Testing jump host ($JUMP_ALIAS)..."
if ssh -o ConnectTimeout=5 -o BatchMode=yes "$JUMP_ALIAS" "echo 'connected'" 2>/dev/null; then
    echo "[OK] Jump host reachable"

    echo ""
    echo "Testing target via jump host ($TARGET_ALIAS)..."
    if ssh -o ConnectTimeout=10 -o BatchMode=yes "$TARGET_ALIAS" "echo 'connected'" 2>/dev/null; then
        echo "[OK] Target reachable via ProxyJump!"
    else
        echo "[INFO] Target not reachable via ProxyJump (may need password auth)"
        echo "       Try manually: ssh $TARGET_ALIAS"
    fi
else
    echo "[INFO] Jump host not reachable (may need password auth or Tailscale)"
    echo "       Try manually: ssh $JUMP_ALIAS"
fi
echo ""

# -----------------------------------------------
# Step 6: SSH key setup hint
# -----------------------------------------------
echo "--- SSH Key Setup (Recommended) ---"
echo ""

if [[ -f "$SSH_DIR/id_ed25519.pub" ]] || [[ -f "$SSH_DIR/id_rsa.pub" ]]; then
    echo "[OK] SSH key pair found."
    echo ""
    echo "  Copy your key to the remote machines for passwordless login:"
    echo "    ssh-copy-id $JUMP_ALIAS"
    echo "    ssh-copy-id $TARGET_ALIAS"
else
    echo "[INFO] No SSH key found. Generate one for passwordless login:"
    echo ""
    echo "    ssh-keygen -t ed25519"
    echo "    ssh-copy-id $JUMP_ALIAS"
    echo "    ssh-copy-id $TARGET_ALIAS"
fi
echo ""

# -----------------------------------------------
# Summary
# -----------------------------------------------
echo "============================================"
echo "  SSH Config Setup Complete!"
echo "============================================"
echo ""
echo "  Quick commands:"
echo "    ssh $JUMP_ALIAS          Direct to jump host"
echo "    ssh $TARGET_ALIAS        Auto-hop through jump host"
if [[ -n "$TARGET_IP" ]]; then
    echo "    ssh ${TARGET_ALIAS}-ip   Fallback via IP"
fi
echo ""
echo "  Config file: $SSH_CONFIG"
echo "  See docs/ssh-config-proxyjump.md for advanced patterns."
echo ""
